// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiddlewareApp.Database;

#nullable disable

namespace MiddlewareApp.Migrations
{
    [DbContext(typeof(ThisDbContext))]
    partial class ThisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiddlewareApp.Model.Entity.Adventurer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("FightingClass")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("XP")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Adventurers", t =>
                        {
                            t.HasCheckConstraint("CK_Adventurers_FightingClass_MinLength", "LEN([FightingClass]) >= 1");

                            t.HasCheckConstraint("CK_Adventurers_Level_Range", "[Level] BETWEEN 1 AND 2147483647");

                            t.HasCheckConstraint("CK_Adventurers_Name_MinLength", "LEN([Name]) >= 1");

                            t.HasCheckConstraint("CK_Adventurers_XP_Range", "[XP] BETWEEN 0 AND 2147483647");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
